image: gitpod/workspace-base

tasks:
- name: install mamba
  command: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n annotation -c bioconda star scallop samtools -y
    mamba activate annotation

    mkdir data; cd data
    wget https://ftp.ebi.ac.uk/pub/training/2023/Introduction-to-RNA-Seq-and-functional-interpretation-2023/annotating-the-genome/data/2cell_chr12_R1.fastq
    wget https://ftp.ebi.ac.uk/pub/training/2023/Introduction-to-RNA-Seq-and-functional-interpretation-2023/annotating-the-genome/data/2cell_chr12_R2.fastq
    wget https://ftp.ebi.ac.uk/pub/training/2023/Introduction-to-RNA-Seq-and-functional-interpretation-2023/annotating-the-genome/data/6hpf_chr12_R1.fastq
    wget https://ftp.ebi.ac.uk/pub/training/2023/Introduction-to-RNA-Seq-and-functional-interpretation-2023/annotating-the-genome/data/6hpf_chr12_R2.fastq

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
